### ISSUE TITLE
Crash on Startup with New Farmers Delight Update

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [ianm1647/farmersknives#3] opened 2022-08-12 19:26 UTC
[crash-2022-08-12_15.19.57-client.txt](https://github.com/ianm1647/farmersknives/files/9329397/crash-2022-08-12_15.19.57-client.txt)

**Comment by bvnniz** [comment] 2022-08-15 17:02
i'm having an issue with the update as well... i went to the curseforge discord to ask for a "crash report translation" and the moderator told me that it was an error caused by farmer's knives. i don't know whether i should just... remove the mod? but, if i remove farmer's knives... will it mess up my saves? 

SOS T^T

[crash-2022-08-15_12.49.49-client-bvnniz.txt](https://github.com/ianm1647/farmersknives/files/9338674/crash-2022-08-15_12.49.49-client-bvnniz.txt)

**Comment by UrBoiTom** [comment] 2022-08-27 21:40
>will it mess up my saves?
It shouldn't, but it will delete any items added by the mod so, if they're very valuable to you, I would wait until this issue is fixed

**Comment by ianm1647** [comment] 2022-08-28 03:12
update your mod, and it should be fixed

**Closed as completed by ianm1647** 2022-08-28 03:12 UTC
